name: Inspect Code

on:
  pull_request:
    branches: [main]

jobs:
  inspect-code:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x.x"

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
          restore-keys: Library

      - name: Build project solution files
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: Packages.Rider.Editor.RiderScriptEditor.SyncSolution
          targetPlatform: StandaloneWindows64

      - name: Run InspectCode
        uses: muno92/resharper_inspectcode@latest
        with:
          solutionPath: ./workspace.sln
